# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\guilh\Documents\PRINT\design\CadastrarAnimal.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Cadastrar(object):
    def setupUi(self, Cadastrar):
        Cadastrar.setObjectName("Cadastrar")
        Cadastrar.resize(900, 600)
        Cadastrar.setMinimumSize(QtCore.QSize(900, 240))
        Cadastrar.setMaximumSize(QtCore.QSize(900, 600))
        self.navegation = QtWidgets.QFrame(Cadastrar)
        self.navegation.setGeometry(QtCore.QRect(0, 0, 221, 741))
        self.navegation.setStyleSheet("background-color: rgb(48, 68, 86)")
        self.navegation.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.navegation.setFrameShadow(QtWidgets.QFrame.Raised)
        self.navegation.setObjectName("navegation")
        self.btnInicio = QtWidgets.QPushButton(self.navegation)
        self.btnInicio.setGeometry(QtCore.QRect(0, 110, 221, 101))
        self.btnInicio.setAutoFillBackground(False)
        self.btnInicio.setStyleSheet("background-color: rgb(48, 68, 86);\n"
"color: white;")
        self.btnInicio.setObjectName("btnInicio")
        self.btnCadastrar = QtWidgets.QPushButton(self.navegation)
        self.btnCadastrar.setGeometry(QtCore.QRect(0, 210, 221, 101))
        self.btnCadastrar.setAutoFillBackground(False)
        self.btnCadastrar.setStyleSheet("background-color: rgb(91, 113, 133);\n"
"color: white;")
        self.btnCadastrar.setObjectName("btnCadastrar")
        self.healthypets = QtWidgets.QPushButton(self.navegation)
        self.healthypets.setEnabled(False)
        self.healthypets.setGeometry(QtCore.QRect(0, 0, 221, 111))
        self.healthypets.setAccessibleName("")
        self.healthypets.setAutoFillBackground(False)
        self.healthypets.setStyleSheet("background-color: rgb(91, 113, 133);\n"
"color: white;")
        self.healthypets.setObjectName("healthypets")
        self.container = QtWidgets.QFrame(Cadastrar)
        self.container.setGeometry(QtCore.QRect(220, 0, 920, 600))
        self.container.setMinimumSize(QtCore.QSize(920, 600))
        self.container.setMaximumSize(QtCore.QSize(920, 740))
        self.container.setStyleSheet("background-color:rgb(201, 201, 201)")
        self.container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.container.setObjectName("container")
        self.txtCadastrar = QtWidgets.QLabel(self.container)
        self.txtCadastrar.setGeometry(QtCore.QRect(30, 10, 291, 51))
        self.txtCadastrar.setStyleSheet("position: absolute;\n"
"width: 397px;\n"
"height: 36px;\n"
"left: 299px;\n"
"top: 80px;\n"
"\n"
"font-family: \'Inter\';\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size: 32px;\n"
"line-height: 39px;\n"
"text-align: center;\n"
"\n"
"color: white;\n"
"")
        self.txtCadastrar.setObjectName("txtCadastrar")
        self.frame = QtWidgets.QFrame(self.container)
        self.frame.setGeometry(QtCore.QRect(20, 60, 621, 401))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.nomeAnimal = QtWidgets.QLabel(self.frame)
        self.nomeAnimal.setGeometry(QtCore.QRect(30, 30, 171, 21))
        self.nomeAnimal.setStyleSheet("position: absolute;\n"
"width: 184px;\n"
"height: 24px;\n"
"left: 420px;\n"
"top: 277px;\n"
"\n"
"font-family: \'Inter\';\n"
"font-style: normal;\n"
"font-weight: 300;\n"
"font-size: 20px;\n"
"line-height: 24px;\n"
"text-align: center;\n"
"\n"
"color: #000000;")
        self.nomeAnimal.setObjectName("nomeAnimal")
        self.porte = QtWidgets.QLabel(self.frame)
        self.porte.setGeometry(QtCore.QRect(30, 170, 71, 31))
        self.porte.setStyleSheet("position: absolute;\n"
"width: 184px;\n"
"height: 24px;\n"
"left: 420px;\n"
"top: 277px;\n"
"\n"
"font-family: \'Inter\';\n"
"font-style: normal;\n"
"font-weight: 300;\n"
"font-size: 20px;\n"
"line-height: 24px;\n"
"text-align: center;\n"
"\n"
"color: #000000;")
        self.porte.setObjectName("porte")
        self.raca = QtWidgets.QLabel(self.frame)
        self.raca.setGeometry(QtCore.QRect(30, 130, 51, 21))
        self.raca.setStyleSheet("position: absolute;\n"
"width: 184px;\n"
"height: 24px;\n"
"left: 420px;\n"
"top: 277px;\n"
"\n"
"font-family: \'Inter\';\n"
"font-style: normal;\n"
"font-weight: 300;\n"
"font-size: 20px;\n"
"line-height: 24px;\n"
"text-align: center;\n"
"\n"
"color: #000000;")
        self.raca.setObjectName("raca")
        self.racao = QtWidgets.QLabel(self.frame)
        self.racao.setGeometry(QtCore.QRect(330, 220, 101, 41))
        self.racao.setStyleSheet("position: absolute;\n"
"width: 184px;\n"
"height: 24px;\n"
"left: 420px;\n"
"top: 277px;\n"
"\n"
"font-family: \'Inter\';\n"
"font-style: normal;\n"
"font-weight: 300;\n"
"font-size: 20px;\n"
"line-height: 24px;\n"
"text-align: center;\n"
"\n"
"color: #000000;")
        self.racao.setObjectName("racao")
        self.status = QtWidgets.QLabel(self.frame)
        self.status.setGeometry(QtCore.QRect(310, 180, 81, 16))
        self.status.setStyleSheet("position: absolute;\n"
"width: 184px;\n"
"height: 24px;\n"
"left: 420px;\n"
"top: 277px;\n"
"\n"
"font-family: \'Inter\';\n"
"font-style: normal;\n"
"font-weight: 300;\n"
"font-size: 20px;\n"
"line-height: 24px;\n"
"text-align: center;\n"
"\n"
"color: #000000;")
        self.status.setObjectName("status")
        self.tutor = QtWidgets.QLabel(self.frame)
        self.tutor.setGeometry(QtCore.QRect(30, 280, 141, 20))
        self.tutor.setStyleSheet("position: absolute;\n"
"width: 184px;\n"
"height: 24px;\n"
"left: 420px;\n"
"top: 277px;\n"
"\n"
"font-family: \'Inter\';\n"
"font-style: normal;\n"
"font-weight: 300;\n"
"font-size: 20px;\n"
"line-height: 24px;\n"
"text-align: center;\n"
"\n"
"color: #000000;")
        self.tutor.setObjectName("tutor")
        self.tipo = QtWidgets.QLabel(self.frame)
        self.tipo.setGeometry(QtCore.QRect(400, 80, 51, 21))
        self.tipo.setStyleSheet("position: absolute;\n"
"width: 184px;\n"
"height: 24px;\n"
"left: 420px;\n"
"top: 277px;\n"
"\n"
"font-family: \'Inter\';\n"
"font-style: normal;\n"
"font-weight: 300;\n"
"font-size: 20px;\n"
"line-height: 24px;\n"
"text-align: center;\n"
"\n"
"color: #000000;")
        self.tipo.setObjectName("tipo")
        self.campoNomeAnimal = QtWidgets.QTextEdit(self.frame)
        self.campoNomeAnimal.setGeometry(QtCore.QRect(210, 20, 391, 41))
        self.campoNomeAnimal.setStyleSheet("position: absolute;\n"
"width: 692px;\n"
"height: 51px;\n"
"left: 625px;\n"
"top: 264px;\n"
"\n"
"background: #D9D9D9;\n"
"border-radius: 8px;")
        self.campoNomeAnimal.setObjectName("campoNomeAnimal")
        self.campoTipo = QtWidgets.QTextEdit(self.frame)
        self.campoTipo.setGeometry(QtCore.QRect(450, 70, 151, 41))
        self.campoTipo.setStyleSheet("position: absolute;\n"
"width: 692px;\n"
"height: 51px;\n"
"left: 625px;\n"
"top: 264px;\n"
"\n"
"background: #D9D9D9;\n"
"border-radius: 8px;")
        self.campoTipo.setObjectName("campoTipo")
        self.campoRaca = QtWidgets.QTextEdit(self.frame)
        self.campoRaca.setGeometry(QtCore.QRect(100, 120, 201, 41))
        self.campoRaca.setStyleSheet("position: absolute;\n"
"width: 692px;\n"
"height: 51px;\n"
"left: 625px;\n"
"top: 264px;\n"
"\n"
"background: #D9D9D9;\n"
"border-radius: 8px;")
        self.campoRaca.setObjectName("campoRaca")
        self.campoPorte = QtWidgets.QTextEdit(self.frame)
        self.campoPorte.setGeometry(QtCore.QRect(100, 170, 191, 41))
        self.campoPorte.setStyleSheet("position: absolute;\n"
"width: 692px;\n"
"height: 51px;\n"
"left: 625px;\n"
"top: 264px;\n"
"\n"
"background: #D9D9D9;\n"
"border-radius: 8px;")
        self.campoPorte.setObjectName("campoPorte")
        self.campoRacao = QtWidgets.QTextEdit(self.frame)
        self.campoRacao.setGeometry(QtCore.QRect(400, 220, 201, 41))
        self.campoRacao.setStyleSheet("position: absolute;\n"
"width: 692px;\n"
"height: 51px;\n"
"left: 625px;\n"
"top: 264px;\n"
"\n"
"background: #D9D9D9;\n"
"border-radius: 8px;")
        self.campoRacao.setObjectName("campoRacao")
        self.campoStatus = QtWidgets.QTextEdit(self.frame)
        self.campoStatus.setGeometry(QtCore.QRect(400, 170, 201, 41))
        self.campoStatus.setStyleSheet("position: absolute;\n"
"width: 692px;\n"
"height: 51px;\n"
"left: 625px;\n"
"top: 264px;\n"
"\n"
"background: #D9D9D9;\n"
"border-radius: 8px;")
        self.campoStatus.setObjectName("campoStatus")
        self.campoBuscarCliente = QtWidgets.QTextEdit(self.frame)
        self.campoBuscarCliente.setGeometry(QtCore.QRect(180, 270, 421, 41))
        self.campoBuscarCliente.setStyleSheet("position: absolute;\n"
"width: 692px;\n"
"height: 51px;\n"
"left: 625px;\n"
"top: 264px;\n"
"\n"
"background: #D9D9D9;\n"
"border-radius: 8px;")
        self.campoBuscarCliente.setObjectName("campoBuscarCliente")
        self.campoSexo = QtWidgets.QTextEdit(self.frame)
        self.campoSexo.setGeometry(QtCore.QRect(380, 120, 221, 41))
        self.campoSexo.setStyleSheet("position: absolute;\n"
"width: 692px;\n"
"height: 51px;\n"
"left: 625px;\n"
"top: 264px;\n"
"\n"
"background: #D9D9D9;\n"
"border-radius: 8px;")
        self.campoSexo.setObjectName("campoSexo")
        self.sexo = QtWidgets.QLabel(self.frame)
        self.sexo.setGeometry(QtCore.QRect(320, 130, 51, 21))
        self.sexo.setStyleSheet("position: absolute;\n"
"width: 184px;\n"
"height: 24px;\n"
"left: 420px;\n"
"top: 277px;\n"
"\n"
"font-family: \'Inter\';\n"
"font-style: normal;\n"
"font-weight: 300;\n"
"font-size: 20px;\n"
"line-height: 24px;\n"
"text-align: center;\n"
"\n"
"color: #000000;")
        self.sexo.setObjectName("sexo")
        self.idade = QtWidgets.QLabel(self.frame)
        self.idade.setGeometry(QtCore.QRect(30, 80, 61, 21))
        self.idade.setStyleSheet("position: absolute;\n"
"width: 184px;\n"
"height: 24px;\n"
"left: 420px;\n"
"top: 277px;\n"
"\n"
"font-family: \'Inter\';\n"
"font-style: normal;\n"
"font-weight: 300;\n"
"font-size: 20px;\n"
"line-height: 24px;\n"
"text-align: center;\n"
"\n"
"color: #000000;")
        self.idade.setObjectName("idade")
        self.campoIdade = QtWidgets.QTextEdit(self.frame)
        self.campoIdade.setGeometry(QtCore.QRect(100, 70, 61, 41))
        self.campoIdade.setStyleSheet("position: absolute;\n"
"width: 692px;\n"
"height: 51px;\n"
"left: 625px;\n"
"top: 264px;\n"
"\n"
"background: #D9D9D9;\n"
"border-radius: 8px;")
        self.campoIdade.setObjectName("campoIdade")
        self.peso = QtWidgets.QLabel(self.frame)
        self.peso.setGeometry(QtCore.QRect(200, 80, 61, 20))
        self.peso.setStyleSheet("position: absolute;\n"
"width: 184px;\n"
"height: 24px;\n"
"left: 420px;\n"
"top: 277px;\n"
"\n"
"font-family: \'Inter\';\n"
"font-style: normal;\n"
"font-weight: 300;\n"
"font-size: 20px;\n"
"line-height: 24px;\n"
"text-align: center;\n"
"\n"
"color: #000000;")
        self.peso.setObjectName("peso")
        self.campoPeso = QtWidgets.QTextEdit(self.frame)
        self.campoPeso.setGeometry(QtCore.QRect(250, 70, 101, 41))
        self.campoPeso.setStyleSheet("position: absolute;\n"
"width: 692px;\n"
"height: 51px;\n"
"left: 625px;\n"
"top: 264px;\n"
"\n"
"background: #D9D9D9;\n"
"border-radius: 8px;")
        self.campoPeso.setObjectName("campoPeso")
        self.btnSalvar = QtWidgets.QPushButton(self.container)
        self.btnSalvar.setGeometry(QtCore.QRect(20, 470, 141, 61))
        self.btnSalvar.setStyleSheet("position: absolute;\n"
"width: 251px;\n"
"height: 66px;\n"
"left: 381px;\n"
"top: 884px;\n"
"\n"
"background-color: rgb(85, 170, 127);\n"
"border-radius: 27px;\n"
"\n"
"font-family: \'Inter\';\n"
"font-style: normal;\n"
"font-weight: 700;\n"
"font-size: 20px;\n"
"line-height: 24px;\n"
"text-align: center;\n"
"\n"
"color: #FFFFFF;")
        self.btnSalvar.setObjectName("btnSalvar")
        self.btnAtualizar = QtWidgets.QPushButton(self.container)
        self.btnAtualizar.setGeometry(QtCore.QRect(500, 470, 141, 61))
        self.btnAtualizar.setStyleSheet("position: absolute;\n"
"width: 251px;\n"
"height: 66px;\n"
"left: 381px;\n"
"top: 884px;\n"
"\n"
"background: #304456;\n"
"border-radius: 27px;\n"
"\n"
"font-family: \'Inter\';\n"
"font-style: normal;\n"
"font-weight: 700;\n"
"font-size: 20px;\n"
"line-height: 24px;\n"
"text-align: center;\n"
"\n"
"color: #FFFFFF;")
        self.btnAtualizar.setObjectName("btnAtualizar")

        self.retranslateUi(Cadastrar)
        QtCore.QMetaObject.connectSlotsByName(Cadastrar)

    def retranslateUi(self, Cadastrar):
        _translate = QtCore.QCoreApplication.translate
        Cadastrar.setWindowTitle(_translate("Cadastrar", "Cadastrar"))
        self.btnInicio.setText(_translate("Cadastrar", "INICIO"))
        self.btnCadastrar.setText(_translate("Cadastrar", "CADASTRAR"))
        self.healthypets.setText(_translate("Cadastrar", "HEALTHY PETS"))
        self.txtCadastrar.setText(_translate("Cadastrar", "Cadastrar Animal"))
        self.nomeAnimal.setText(_translate("Cadastrar", "NOME DO ANIMAL"))
        self.porte.setText(_translate("Cadastrar", "PORTE"))
        self.raca.setText(_translate("Cadastrar", "RAÇA"))
        self.racao.setText(_translate("Cadastrar", "RAÇÃO"))
        self.status.setText(_translate("Cadastrar", "STATUS"))
        self.tutor.setText(_translate("Cadastrar", "BUSCAR TUTOR"))
        self.tipo.setText(_translate("Cadastrar", "TIPO"))
        self.sexo.setText(_translate("Cadastrar", "SEXO"))
        self.idade.setText(_translate("Cadastrar", "IDADE"))
        self.peso.setText(_translate("Cadastrar", "PESO"))
        self.btnSalvar.setText(_translate("Cadastrar", "SALVAR"))
        self.btnAtualizar.setText(_translate("Cadastrar", "LISTAR"))
